### ISSUE TITLE
The third party pygmo

### ISSUE THREAD

**Issue by outofstyle** [GuillaumeBriffoteaux/pySAEA#2]
Hi, I'm a student studying the surrogate-assisted evolutionary algorithm, but i can't install the pygmo because of it had upgrage to the pygmo2, may you offer a useful pygmo?

**Comment by GuillaumeBriffoteaux** [comment]
Hi!

Thank you for considering pySBO!

To install pygmo2, please follow the installation tutorial available at https://esa.github.io/pygmo2/install.html. Consider installing pygmo2 with Conda. Last time I tried with Pip, it didn't work.

I'm on holiday until 3rd January 2023. If you need more assistance to setup pySBO, I will be pleased to help you when I go back to work.

Best regards.

**Comment by GuillaumeBriffoteaux** [comment]
Hi,

I have just updated the dependencies' versions and I have added a detailed installation tutorial (for both Linux and Windows) on the Read the Docs page. I now consider this thread closed.
